name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - 'release_*'

jobs:
  runs-on: windows-latest
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      - name: tests
        run: |
          export PYTHONPATH=$PWD && pytest
      - name: mypy
        run: |
          pip install mypy
          mypy .
      - name: flake8
        run: |
          pip install flake8
          flake8 --benchmark .
      - name: bandit
        run: |
          pip install bandit
          bandit -r asynchuobi/